version: '3.5'

services:

  #PHP Service
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    container_name: app_tbee
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
      - laravel_echo_server

  #Nginx Service
  websever:
    image: nginx:1.14-alpine
    container_name: web_tbee
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  # DB UI management service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin_tbee
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql_tbee
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - .docker/data/db:/var/lib/mysql/

  laravel_echo_server:
    build:
      context: .docker/laravel-echo-server
      dockerfile: Dockerfile
    container_name: echo_server_tbee
    volumes:
      - .env:/app/.env
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    container_name: redis_tbee
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
